# The serial port to use:
port: '/dev/cu.usbmodem141301'

# If false, opens the GUI but doesn't read data:
read_from_esp: True

# Number of samples to display in the graphs:
nsamples: 100

# time in seconds between two data retrieval
sampling_interval: 0.1

# Variables to display in the graphs (must match names in the ESP):
plot_top_var: mve
plot_mid_var: vti
plot_bot_var: vte

# Control Start/Stop Auto/Man behavior
start_mode_timeout: 2000 # [ms] between pressing Start and allowing Stop (max 3000)

# Setup monitors (key value monitor_* must match widget name in mainwindow.ui)
monitor_top: 
    name: "Insp. Press."
    min: 10
    init: 30
    max: 80
    step: 1
    dec_precision: 0
    units: "(mbar)"
    color: "yellow"
    alarmcolor: "red"

monitor_mid: 
    name: "V<sub>tidal</sub>"
    min: 50
    init: 100
    max: 1500
    step: 100
    dec_precision: 0
    units: "mL"
    color: "limegreen"
    alarmcolor: "red"

monitor_bot: 
    name: "MVe"
    min: 2 
    init: 10
    max: 20
    step: 1
    dec_precision: 0
    units: "(slpm)"
    color: "cyan"
    alarmcolor: "red"
