# The serial port to use:
port: '/dev/cu.usbmodem141301'

# If false, opens the GUI but doesn't read data:
read_from_esp: True

# Number of samples to display in the graphs:
nsamples: 100

# time in seconds between two data retrieval
sampling_interval: 0.1

# The parameters that will be read from the ESP and stored for possible use
read_params: ['pressure', 'flow', 'o2', 'bpm', 'all']

# The parameters that can be set on the ESP
# The values below must match those used in the ESP
esp_settable_param:
    respiratory_rate: 'rate'
    insp_expir_ratio: 'ratio'
    pressure_trigger: 'assist_ptrigger'
    flow_trigger: 'assist_flow_min'


# This is the string returned by the ESP in case of success
return_success_code: 'OK'

# Thickness of the lines drawn in the plots
line_width: 1

# The widht of the line that draws the axes
axis_line_width: 1

# The color used to draw the axes
axis_line_color: "rgb(255,228,181)"

# Shows the values that will trigger the alarms directly on the plots
show_safe_ranges_on_graphs: True

# Toggles the x axis labels in the graphs (specifcally, the 'Time [s]' label)
show_x_axis_labels: True

# Toggles the x axis ticks in the graphs (specifcally, the numbers on the x axis)
show_x_axis_ticks: True

# The units used for each variable:
var_units: 
    pressure: 'mbar'
    flow: 'lpm'
    o2: '%'
    bpm: 'Hz'
    volume: 'mL'

# Control Start/Stop Auto/Man behavior
start_mode_timeout: 2000 # [ms] between pressing Start and allowing Stop (max 3000)


# Setup monitors (key value monitor_* must match widget name in mainwindow.ui)
# Variables to display in the graphs are in plot_var 
# and the must match names in the ESP or an available function
monitor_top: 
    name: "Insp. Press."
    min: 10
    init: 30
    max: 80
    step: 1
    dec_precision: 0
    units: "(mbar)"
    color: "rgb(255,255,0)"
    alarmcolor: "red"
    plot_var: pressure

monitor_mid: 
    name: "V<sub>tidal</sub>"
    min: 50
    init: 100
    max: 1500
    step: 100
    dec_precision: 0
    units: "mL"
    color: "rgb(50,205,50)"
    alarmcolor: "red"
    plot_var: volume

monitor_bot: 
    name: "MVe"
    min: 2 
    init: 10
    max: 20
    step: 1
    dec_precision: 0
    units: "(slpm)"
    color: "rgb(0,255,255)"
    alarmcolor: "red"
    plot_var: flow







#
# Automatic Mode
#
# Note: can only have max 6 presets for now.

# Respiration Rate (breaths per minute)
respiratory_rate:
    name: "Resp. Rate"
    default: 12
    min: 4
    max: 50
    step: 1
    current: None
    units: "b/min"
    presets:
        - 5
        - 10
        - 15
        - 20
        - 25
        - 30

# Inspiration/Expiration
insp_expir_ratio:
    name: "Insp./Expir."
    default:  0.5
    min: 0.33
    max: 1.
    step: 0.01
    current: None
    units: "ratio"
    show_fraction: True
    presets:
        - 1 # 1:1
        - 2 # 1:2
        - 3 # 1:3


#
# Assisted Mode
#

# The trigger that starts the respiration
pressure_trigger: 
    default: 1.
    min: 0.
    max: 10.
    current: None
    presets:
        - 80 # Hard
        - 60 # Medium
        - 30 # Normal
        - 10 # Soft


# 
flow_trigger: 
    default: 1.
    min: 0.
    max: 10.
    current: None
    presets:
        - 10
        - 15
        - 20
        - 25
        - 30
        - 35

#
minimal_resp_rate:
    default: 1.
    min: 0.
    max: 10.
    current: None
    presets:
        - 3
        - 5
        - 10
        - 15

enable_backup: False
